version: '2'
services:
    lectureplanner-app:
        image: lectureplanner
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://lectureplanner-postgresql:5432/LecturePlanner
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    lectureplanner-postgresql:
        extends:
            file: postgresql.yml
            service: lectureplanner-postgresql
